package com.example.minifinancieraapp.ui.models

data class ClienteModel(
    val id: String = "",
    val nombre: String = "",
    val identidad: String = "",
    val telefono: String = "",
    val direccionCasa: String = "",
    val direccionNegocio: String = "",
    val estadoCivil: String = "",
    val nombreConyuge: String = "",
    val identidadConyuge: String = "",
    val telefonoConyuge: String = "",
    val referencia1Nombre: String = "",
    val referencia1Identidad: String = "",
    val referencia1Telefono: String = "",
    val referencia1Parentesco: String = "",
    val referencia1Direccion: String = "",
    val referencia2Nombre: String = "",
    val referencia2Identidad: String = "",
    val referencia2Telefono: String = "",
    val referencia2Parentesco: String = "",
    val referencia2Direccion: String = "",
    val fotoCasaUrl: String = "",
    val fotoNegocioUrl: String = "",
    val fotoClienteUrl: String = "",
    val fotoIdentidadFrenteUrl: String = "",
    val fotoIdentidadReversoUrl: String = "",
    val fotoReciboLuzUrl: String = "",
    val garantiaTexto: String = "",
    val garantiaFotoUrl: String = "",
    val estado: String = "activo",
    val tienePrestamo: Boolean = false,
    val cobradorAsignado: String = ""
)
